import{buildIdempotencyKey}from'../capture/deduplicate';import type{CaptureIssueMessage,CaptureSubmitMessage,CaptureVerdictMessage}from'../messaging/messages';
export interface StorageLike{get(key:string):Promise<Record<string,unknown>>;set(items:Record<string,unknown>):Promise<void>}
export interface CaptureEntry extends Omit<CaptureSubmitMessage,'type'>{idempotencyKey:string;verdict?:string;rawVerdict?:string;runtimeText?:string;memoryText?:string;errorSummary?:string;verdictAt?:number;createdAt:number;updatedAt:number}
export interface IssueEntry extends Omit<CaptureIssueMessage,'type'>{createdAt:number}
export const LOG_KEY='leetx:captureLog',ISSUE_KEY='leetx:captureIssues';const MAX_ENTRIES=500,MAX_ISSUES=200;
export function makeInMemoryStorage():StorageLike{const data:Record<string,unknown>={};return{get:key=>Promise.resolve({[key]:data[key]}),set:items=>{Object.assign(data,items);return Promise.resolve()}}}
async function readLog(storage:StorageLike):Promise<CaptureEntry[]>{const raw=(await storage.get(LOG_KEY))[LOG_KEY];return Array.isArray(raw)?raw as CaptureEntry[]:[]}
export async function saveSubmit(storage:StorageLike,msg:CaptureSubmitMessage,now:()=>number=Date.now):Promise<'saved'|'duplicate'|'finalized'>{const key=buildIdempotencyKey(msg);const log=await readLog(storage);const exact=log.find(entry=>entry.idempotencyKey===key);const related=msg.verdict?log.filter(entry=>entry.platform===msg.platform&&entry.problemKey===msg.problemKey&&entry.codeHash===msg.codeHash&&Math.abs(entry.submittedAt-msg.submittedAt)<30_000):[];const existing=exact??related.reduce<CaptureEntry|undefined>((closest,entry)=>!closest||Math.abs(entry.submittedAt-msg.submittedAt)<Math.abs(closest.submittedAt-msg.submittedAt)?entry:closest,undefined);if(existing){if(!msg.verdict)return'duplicate';Object.assign(existing,{title:msg.title&&msg.title!==msg.problemKey?msg.title:existing.title,accountKey:existing.accountKey==='anonymous'?msg.accountKey:existing.accountKey,language:existing.language||msg.language,verdict:msg.verdict,rawVerdict:msg.rawVerdict,runtimeText:msg.runtimeText,memoryText:msg.memoryText,verdictAt:msg.verdictAt,updatedAt:now()});const duplicates=new Set(related.filter(entry=>entry!==existing));await storage.set({[LOG_KEY]:log.filter(entry=>!duplicates.has(entry))});return'finalized'}const{type:_type,...fields}=msg;const timestamp=now();log.push({...fields,idempotencyKey:key,createdAt:timestamp,updatedAt:timestamp});await storage.set({[LOG_KEY]:log.slice(-MAX_ENTRIES)});return'saved'}
export async function mergeVerdict(storage:StorageLike,msg:CaptureVerdictMessage,now:()=>number=Date.now):Promise<'merged'|'orphan'>{const log=await readLog(storage);const entry=log.find(e=>e.captureId===msg.captureId);if(!entry)return'orphan';Object.assign(entry,{verdict:msg.verdict,rawVerdict:msg.rawVerdict,runtimeText:msg.runtimeText,memoryText:msg.memoryText,errorSummary:msg.errorSummary,verdictAt:msg.observedAt,updatedAt:now()});await storage.set({[LOG_KEY]:log});return'merged'}
export async function appendIssue(storage:StorageLike,msg:CaptureIssueMessage,now:()=>number=Date.now):Promise<void>{const raw=(await storage.get(ISSUE_KEY))[ISSUE_KEY];const issues=Array.isArray(raw)?raw as IssueEntry[]:[];const{type:_type,...fields}=msg;issues.push({...fields,createdAt:now()});await storage.set({[ISSUE_KEY]:issues.slice(-MAX_ISSUES)})}
export async function listCaptures(storage:StorageLike):Promise<{captures:CaptureEntry[];issues:IssueEntry[]}>{const captures=await readLog(storage);const localizedTitles=new Map<string,string>();for(const entry of captures)if(entry.title&&entry.title!==entry.problemKey)localizedTitles.set(`${entry.platform}:${entry.problemKey}`,entry.title);const normalized=captures.map(entry=>{const title=localizedTitles.get(`${entry.platform}:${entry.problemKey}`);return title&&entry.title===entry.problemKey?{...entry,title}:entry});const raw=(await storage.get(ISSUE_KEY))[ISSUE_KEY];const issues=Array.isArray(raw)?raw as IssueEntry[]:[];return{captures:[...normalized].reverse(),issues:[...issues].reverse()}}
